title: Learning a Risk-Averse Locomotion Policy from Uncertainty Estimates
description: Thomas B. Brunner*, Takahiro Miki*, Josip Josifovski, Joonho Lee, Alois Knoll, Marco Hutter
theme: jekyll-theme-cayman
